import type { LucideIcon } from "lucide-react"
import {
  Home,
  Shirt,
  Shield,
  ShoppingCart,
  Heart,
  User,
  Bot,
  Phone,
  LogIn,
  UserPlus,
} from "lucide-react"
import type { Product } from "@/types"

export interface NavLinkItem {
  href: string
  label: string
  icon: LucideIcon
}

export const NAV_LINKS: NavLinkItem[] = [
  { href: "/", label: "Home", icon: Home },
  { href: "/sportswear", label: "Sportswear", icon: Shirt },
  { href: "/uniforms", label: "Uniforms", icon: Shield },
  { href: "/contact", label: "Contact Us", icon: Phone },
  // { href: "/cart", label: "Cart", icon: ShoppingCart },
  { href: "/wishlist", label: "Wishlist", icon: Heart },
  { href: "/profile", label: "Profile", icon: User },
  // { href: '/login', label: 'Login', icon: LogIn }, // Example conditional link
]
export const MOCK_PRODUCTS: Product[] = [
  // Sportswear (12 items)
  {
    id: "sw1",
    name: "Pro Performance T-Shirt",
    category: "Sportswear",
    price: 29.99,
    description:
      "Lightweight, breathable fabric for peak performance. Moisture-wicking technology keeps you dry.",
    images: [
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance shirt",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "White" },
      { type: "Size", value: "S" },
      { type: "Size", value: "M" },
    ],
    rating: 4.5,
    reviews: 120,
  },
  {
    id: "sw2",
    name: "FlexFit Training Shorts",
    category: "Sportswear",
    price: 34.99,
    description:
      "Stretchable and comfortable shorts perfect for any workout with secure pockets.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shorts",
    variants: [
      { type: "Color", value: "Navy" },
      { type: "Color", value: "Gray" },
    ],
    rating: 4.2,
    reviews: 95,
  },
  {
    id: "sw3",
    name: "All-Weather Running Jacket",
    category: "Sportswear",
    price: 89.99,
    description:
      "Water-resistant and windproof jacket for running in any condition with reflective details.",
    images: [
      "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "running jacket",
    variants: [
      { type: "Color", value: "Neon Yellow" },
      { type: "Color", value: "Black" },
    ],
    rating: 4.7,
    reviews: 150,
  },
  {
    id: "sw4",
    name: "Yoga Comfort Leggings",
    category: "Sportswear",
    price: 45.99,
    description:
      "High-waisted leggings with four-way stretch for maximum comfort during yoga.",
    images: [
      "https://images.unsplash.com/photo-1517960413843-0aee8e2d471c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "yoga leggings",
    variants: [
      { type: "Color", value: "Purple" },
      { type: "Color", value: "Teal" },
    ],
    rating: 4.6,
    reviews: 180,
  },
  {
    id: "sw5",
    name: "Compression Sleeveless Top",
    category: "Sportswear",
    price: 39.99,
    description:
      "Muscle-support compression top for intense workouts with breathable fabric.",
    images: [
      "https://images.unsplash.com/photo-1591213953507-48d5f5f9a3ef?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "compression top",
    variants: [],
    rating: 4.4,
    reviews: 75,
  },
  {
    id: "sw6",
    name: "Training Hoodie",
    category: "Sportswear",
    price: 59.99,
    description:
      "Lightweight hoodie with moisture-wicking fabric for warm-up sessions.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training hoodie",
    variants: [],
    rating: 4.3,
    reviews: 110,
  },
  {
    id: "sw7",
    name: "Running Tights",
    category: "Sportswear",
    price: 49.99,
    description:
      "Performance tights with phone pocket and reflective details for night running.",
    images: [
      "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "running tights",
    variants: [],
    rating: 4.5,
    reviews: 92,
  },
  {
    id: "sw8",
    name: "Training Tank Top",
    category: "Sportswear",
    price: 24.99,
    description:
      "Lightweight tank top with ventilation panels for maximum airflow.",
    images: [
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tank",
    variants: [],
    rating: 4.1,
    reviews: 68,
  },
  {
    id: "sw9",
    name: "Thermal Base Layer",
    category: "Sportswear",
    price: 54.99,
    description:
      "Winter training base layer with thermal insulation for cold weather workouts.",
    images: [
      "https://images.unsplash.com/photo-1520004434532-668416a08753?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "thermal base layer",
    variants: [],
    rating: 4.7,
    reviews: 134,
  },
  {
    id: "sw10",
    name: "Training Joggers",
    category: "Sportswear",
    price: 49.99,
    description:
      "Flexible joggers with adjustable waistband and zippered pockets.",
    images: [
      "https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training joggers",
    variants: [],
    rating: 4.4,
    reviews: 87,
  },
  {
    id: "sw11",
    name: "Performance Sports Bra",
    category: "Sportswear",
    price: 39.99,
    description:
      "High-support sports bra with breathable fabric for intense workouts.",
    images: [
      "https://images.unsplash.com/photo-1581009137042-c552e485697a?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports bra",
    variants: [],
    rating: 4.8,
    reviews: 210,
  },
  {
    id: "sw12",
    name: "Training Windbreaker",
    category: "Sportswear",
    price: 64.99,
    description:
      "Lightweight windbreaker with water-resistant coating for outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e4?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training windbreaker",
    variants: [],
    rating: 4.6,
    reviews: 103,
  },

  // Uniforms (12 items)
  {
    id: "u1",
    name: "Elite Soccer Uniform",
    category: "Uniforms",
    price: 79.99,
    description:
      "Complete soccer kit including jersey and shorts. Durable and designed for professional play.",
    images: [
      "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1505843279827-4b2b4e7e8c9a?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "soccer uniform",
    variants: [
      { type: "Color", value: "Team Yellow" },
      { type: "Color", value: "Team Green" },
    ],
    rating: 4.8,
    reviews: 85,
  },
  {
    id: "u2",
    name: "Championship Basketball Jersey",
    category: "Uniforms",
    price: 55.0,
    description:
      "Authentic design basketball jersey. Breathable mesh fabric for ultimate comfort.",
    images: [
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "basketball jersey",
    variants: [
      { type: "Color", value: "Home White" },
      { type: "Color", value: "Away Blue" },
    ],
    rating: 4.9,
    reviews: 210,
  },
  {
    id: "u3",
    name: "Volleyball Team Uniform",
    category: "Uniforms",
    price: 65.99,
    description:
      "Complete volleyball uniform set with jersey and shorts in moisture-wicking fabric.",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "volleyball uniform",
    variants: [],
    rating: 4.7,
    reviews: 76,
  },
  {
    id: "u4",
    name: "Baseball Team Jersey",
    category: "Uniforms",
    price: 59.99,
    description:
      "Traditional button-up baseball jersey with team logo placement options.",
    images: [
      "https://images.unsplash.com/photo-1549633030-94e4e7ad06a3?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "baseball jersey",
    variants: [],
    rating: 4.5,
    reviews: 92,
  },
  {
    id: "u5",
    name: "Rugby Team Kit",
    category: "Uniforms",
    price: 89.99,
    description:
      "Durable rugby jersey with reinforced stitching for intense gameplay.",
    images: [
      "https://images.unsplash.com/photo-1600679472829-3044539ce8ed?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "rugby uniform",
    variants: [],
    rating: 4.8,
    reviews: 64,
  },
  {
    id: "u6",
    name: "Track & Field Singlet",
    category: "Uniforms",
    price: 34.99,
    description:
      "Lightweight singlet for track athletes with breathable mesh panels.",
    images: [
      "https://images.unsplash.com/photo-1519766304817-4f37bda74a2b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "track uniform",
    variants: [],
    rating: 4.3,
    reviews: 58,
  },
  {
    id: "u7",
    name: "Hockey Jersey",
    category: "Uniforms",
    price: 69.99,
    description:
      "Authentic hockey jersey with fight strap and reinforced elbows.",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "hockey jersey",
    variants: [],
    rating: 4.6,
    reviews: 87,
  },
  {
    id: "u8",
    name: "Swim Team Suit",
    category: "Uniforms",
    price: 49.99,
    description:
      "Competition swimsuit with hydrodynamic design for competitive swimmers.",
    images: [
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "swim uniform",
    variants: [],
    rating: 4.7,
    reviews: 103,
  },
  {
    id: "u9",
    name: "Cricket Whites",
    category: "Uniforms",
    price: 74.99,
    description:
      "Traditional cricket uniform with long-sleeve shirt and trousers in breathable fabric.",
    images: [
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "cricket uniform",
    variants: [],
    rating: 4.4,
    reviews: 42,
  },
  {
    id: "u10",
    name: "Lacrosse Uniform",
    category: "Uniforms",
    price: 67.99,
    description:
      "Complete lacrosse uniform with padded jersey and matching shorts.",
    images: [
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "lacrosse uniform",
    variants: [],
    rating: 4.5,
    reviews: 37,
  },
  {
    id: "u11",
    name: "Martial Arts Gi",
    category: "Uniforms",
    price: 59.99,
    description:
      "Traditional martial arts uniform with reinforced stitching for durability.",
    images: [
      "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "martial arts uniform",
    variants: [],
    rating: 4.9,
    reviews: 128,
  },
  {
    id: "u12",
    name: "Cheerleading Uniform",
    category: "Uniforms",
    price: 89.99,
    description:
      "Sparkly cheerleading uniform with skirt and crop top for squad performances.",
    images: [
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "cheerleading uniform",
    variants: [],
    rating: 4.7,
    reviews: 96,
  },

  // Accessories (10 items)
  {
    id: "a1",
    name: "Performance Headband",
    category: "Accessories",
    price: 12.99,
    description:
      "Moisture-wicking headband to keep sweat out of your eyes during workouts.",
    images: [
      "https://images.unsplash.com/photo-1593810450967-f9c42742e326?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "workout headband",
    variants: [],
    rating: 4.3,
    reviews: 145,
  },
  {
    id: "a2",
    name: "Training Gloves",
    category: "Accessories",
    price: 19.99,
    description:
      "Padded workout gloves to protect your hands during weight training.",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training gloves",
    variants: [],
    rating: 4.5,
    reviews: 98,
  },
  {
    id: "a3",
    name: "Running Armband",
    category: "Accessories",
    price: 14.99,
    description:
      "Secure armband to hold your phone while running or working out.",
    images: [
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "phone armband",
    variants: [],
    rating: 4.1,
    reviews: 76,
  },
  {
    id: "a4",
    name: "Yoga Mat",
    category: "Accessories",
    price: 29.99,
    description:
      "Non-slip yoga mat with carrying strap for your practice anywhere.",
    images: [
      "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "yoga mat",
    variants: [],
    rating: 4.8,
    reviews: 210,
  },
  {
    id: "a5",
    name: "Sports Water Bottle",
    category: "Accessories",
    price: 15.99,
    description:
      "BPA-free water bottle with leak-proof lid and measurement markings.",
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "water bottle",
    variants: [],
    rating: 4.6,
    reviews: 187,
  },
  {
    id: "a6",
    name: "Gym Towel",
    category: "Accessories",
    price: 9.99,
    description: "Microfiber gym towel that absorbs sweat and dries quickly.",
    images: [
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "gym towel",
    variants: [],
    rating: 4.4,
    reviews: 132,
  },
  {
    id: "a7",
    name: "Resistance Bands Set",
    category: "Accessories",
    price: 24.99,
    description:
      "Set of 5 resistance bands with different tension levels for versatile workouts.",
    images: [
      "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "resistance bands",
    variants: [],
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "a8",
    name: "Sports Sunglasses",
    category: "Accessories",
    price: 39.99,
    description:
      "UV-protection sunglasses with non-slip grip for outdoor sports.",
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports sunglasses",
    variants: [],
    rating: 4.5,
    reviews: 89,
  },
  {
    id: "a9",
    name: "Running Belt",
    category: "Accessories",
    price: 19.99,
    description:
      "Lightweight running belt with zippered pocket to carry essentials.",
    images: [
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "running belt",
    variants: [],
    rating: 4.2,
    reviews: 67,
  },
  {
    id: "a10",
    name: "Sweat Wristbands",
    category: "Accessories",
    price: 8.99,
    description:
      "Absorbent wristbands to wipe away sweat during intense workouts.",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "wristbands",
    variants: [],
    rating: 4.0,
    reviews: 54,
  },

  // Footwear (10 items)
  {
    id: "f1",
    name: "Running Shoes",
    category: "Footwear",
    price: 99.99,
    description:
      "Lightweight running shoes with responsive cushioning for road running.",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "running shoes",
    variants: [],
    rating: 4.7,
    reviews: 245,
  },
  {
    id: "f2",
    name: "Basketball Shoes",
    category: "Footwear",
    price: 119.99,
    description:
      "High-top basketball shoes with ankle support and responsive cushioning.",
    images: [
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "basketball shoes",
    variants: [],
    rating: 4.8,
    reviews: 187,
  },
  {
    id: "f3",
    name: "Training Cross-Trainers",
    category: "Footwear",
    price: 89.99,
    description:
      "Versatile training shoes for gym workouts and cross-training activities.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "cross trainers",
    variants: [],
    rating: 4.6,
    reviews: 134,
  },
  {
    id: "f4",
    name: "Soccer Cleats",
    category: "Footwear",
    price: 79.99,
    description:
      "Firm ground soccer cleats with synthetic leather for ball control.",
    images: [
      "https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "soccer cleats",
    variants: [],
    rating: 4.5,
    reviews: 98,
  },
  {
    id: "f5",
    name: "Trail Running Shoes",
    category: "Footwear",
    price: 109.99,
    description:
      "Durable trail runners with aggressive tread for off-road running.",
    images: [
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "trail running shoes",
    variants: [],
    rating: 4.7,
    reviews: 112,
  },
  {
    id: "f6",
    name: "Walking Shoes",
    category: "Footwear",
    price: 69.99,
    description:
      "Comfortable walking shoes with arch support for all-day wear.",
    images: [
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "walking shoes",
    variants: [],
    rating: 4.4,
    reviews: 87,
  },
  {
    id: "f7",
    name: "Weightlifting Shoes",
    category: "Footwear",
    price: 129.99,
    description: "Stable lifting shoes with raised heel for proper squat form.",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "weightlifting shoes",
    variants: [],
    rating: 4.9,
    reviews: 76,
  },
  {
    id: "f8",
    name: "Tennis Shoes",
    category: "Footwear",
    price: 89.99,
    description:
      "Court shoes with lateral support for quick movements in tennis.",
    images: [
      "https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "tennis shoes",
    variants: [],
    rating: 4.5,
    reviews: 65,
  },
  {
    id: "f9",
    name: "Minimalist Running Shoes",
    category: "Footwear",
    price: 79.99,
    description: "Zero-drop minimalist shoes for natural running form.",
    images: [
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "minimalist shoes",
    variants: [],
    rating: 4.3,
    reviews: 54,
  },
  {
    id: "f10",
    name: "Track Spikes",
    category: "Footwear",
    price: 89.99,
    description:
      "Lightweight track spikes for sprinting and middle distance running.",
    images: [
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "track spikes",
    variants: [],
    rating: 4.6,
    reviews: 43,
  },
  // Add 6 more mock products for a total of 50
  {
    id: "sw13",
    name: "UltraDry Training Tee",
    category: "Sportswear",
    price: 32.99,
    description: "Quick-dry tee for high-intensity workouts.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tee",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "L" },
    ],
    rating: 4.3,
    reviews: 77,
  },
  {
    id: "sw14",
    name: "Seamless Yoga Shorts",
    category: "Sportswear",
    price: 27.99,
    description: "Seamless shorts for yoga and pilates.",
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "yoga shorts",
    variants: [
      { type: "Color", value: "Pink" },
      { type: "Size", value: "S" },
    ],
    rating: 4.5,
    reviews: 61,
  },
  {
    id: "sw15",
    name: "Pro Mesh Cap",
    category: "Accessories",
    price: 15.99,
    description: "Breathable mesh cap for outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "mesh cap",
    variants: [{ type: "Color", value: "Black" }],
    rating: 4.2,
    reviews: 34,
  },
  {
    id: "sw16",
    name: "Performance Crew Socks",
    category: "Accessories",
    price: 9.99,
    description: "Moisture-wicking crew socks for all sports.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "crew socks",
    variants: [{ type: "Color", value: "White" }],
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "sw17",
    name: "Studio Training Shoes",
    category: "Footwear",
    price: 79.99,
    description: "Lightweight shoes for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "studio shoes",
    variants: [{ type: "Color", value: "Gray" }],
    rating: 4.4,
    reviews: 56,
  },
  {
    id: "sw18",
    name: "All-Weather Sports Duffel",
    category: "Accessories",
    price: 49.99,
    description: "Spacious duffel bag for all your sports gear.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports duffel",
    variants: [{ type: "Color", value: "Navy" }],
    rating: 4.7,
    reviews: 102,
  },
  {
    id: "sw19",
    name: "Active Training Shorts",
    category: "Sportswear",
    price: 36.99,
    description: "Breathable shorts for all types of training.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shorts",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "M" },
    ],
    rating: 4.4,
    reviews: 80,
  },
  {
    id: "sw20",
    name: "Performance Polo Shirt",
    category: "Sportswear",
    price: 42.99,
    description: "Moisture-wicking polo for golf and tennis.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "polo shirt",
    variants: [
      { type: "Color", value: "White" },
      { type: "Size", value: "L" },
    ],
    rating: 4.5,
    reviews: 65,
  },
  {
    id: "sw21",
    name: "Studio Yoga Pants",
    category: "Sportswear",
    price: 39.99,
    description: "Flexible yoga pants for studio sessions.",
    images: [
      "https://images.unsplash.com/photo-1517960413843-0aee8e2d471c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "yoga pants",
    variants: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "S" },
    ],
    rating: 4.6,
    reviews: 90,
  },
  {
    id: "sw22",
    name: "Pro Training Cap",
    category: "Accessories",
    price: 18.99,
    description: "Lightweight cap for sun protection during training.",
    images: [
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training cap",
    variants: [{ type: "Color", value: "Blue" }],
    rating: 4.3,
    reviews: 44,
  },
  {
    id: "sw23",
    name: "Classic Sports Socks",
    category: "Accessories",
    price: 11.99,
    description: "Classic crew socks for all sports.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports socks",
    variants: [{ type: "Color", value: "White" }],
    rating: 4.5,
    reviews: 70,
  },
  {
    id: "sw24",
    name: "Studio Gym Bag",
    category: "Accessories",
    price: 44.99,
    description: "Spacious gym bag for all your essentials.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "gym bag",
    variants: [{ type: "Color", value: "Black" }],
    rating: 4.7,
    reviews: 99,
  },
  {
    id: "sw25",
    name: "All-Weather Training Shoes",
    category: "Footwear",
    price: 89.99,
    description: "Durable shoes for all-weather training.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shoes",
    variants: [{ type: "Color", value: "Black" }],
    rating: 4.6,
    reviews: 120,
  },
  {
    id: "sw26",
    name: "Performance Headband Pro",
    category: "Accessories",
    price: 13.99,
    description: "Advanced headband for sweat control.",
    images: [
      "https://images.unsplash.com/photo-1593810450967-f9c42742e326?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "headband",
    variants: [{ type: "Color", value: "Red" }],
    rating: 4.4,
    reviews: 55,
  },
  {
    id: "sw27",
    name: "Training Water Bottle XL",
    category: "Accessories",
    price: 17.99,
    description: "Extra large water bottle for long workouts.",
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "water bottle",
    variants: [{ type: "Color", value: "Blue" }],
    rating: 4.8,
    reviews: 110,
  },
  {
    id: "sw28",
    name: "Studio Training Mat",
    category: "Accessories",
    price: 29.99,
    description: "Non-slip mat for studio workouts.",
    images: [
      "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training mat",
    variants: [{ type: "Color", value: "Gray" }],
    rating: 4.7,
    reviews: 88,
  },
  {
    id: "sw29",
    name: "Performance Training Gloves",
    category: "Accessories",
    price: 21.99,
    description: "Padded gloves for weight training.",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training gloves",
    variants: [{ type: "Color", value: "Black" }],
    rating: 4.5,
    reviews: 60,
  },
  {
    id: "sw30",
    name: "Active Sports Cap",
    category: "Accessories",
    price: 16.99,
    description: "Lightweight cap for active sports.",
    images: [
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports cap",
    variants: [{ type: "Color", value: "White" }],
    rating: 4.3,
    reviews: 45,
  },
  {
    id: "sw31",
    name: "Studio Performance Tee",
    category: "Sportswear",
    price: 33.99,
    description: "Performance tee for studio workouts.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance tee",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.4,
    reviews: 78,
  },
  {
    id: "sw32",
    name: "All-Weather Training Jacket",
    category: "Sportswear",
    price: 92.99,
    description: "Jacket for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training jacket",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.6,
    reviews: 99,
  },
  {
    id: "sw33",
    name: "Studio Yoga Mat",
    category: "Accessories",
    price: 27.99,
    description: "Yoga mat for studio and home practice.",
    images: [
      "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "yoga mat",
    variants: [{ type: "Color", value: "Purple" }],
    rating: 4.7,
    reviews: 120,
  },
  {
    id: "sw34",
    name: "Performance Sports Socks",
    category: "Accessories",
    price: 12.99,
    description: "Performance socks for all sports.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "sports socks",
    variants: [{ type: "Color", value: "Black" }],
    rating: 4.5,
    reviews: 80,
  },
  {
    id: "sw35",
    name: "Studio Training Shorts",
    category: "Sportswear",
    price: 37.99,
    description: "Shorts for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shorts",
    variants: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "L" },
    ],
    rating: 4.4,
    reviews: 70,
  },
  {
    id: "sw36",
    name: "Performance Training Tank",
    category: "Sportswear",
    price: 28.99,
    description: "Tank top for high-intensity training.",
    images: [
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tank",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.3,
    reviews: 60,
  },
  {
    id: "sw37",
    name: "Studio Performance Shorts",
    category: "Sportswear",
    price: 35.99,
    description: "Performance shorts for studio workouts.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance shorts",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.4,
    reviews: 75,
  },
  {
    id: "sw38",
    name: "All-Weather Training Pants",
    category: "Sportswear",
    price: 59.99,
    description: "Pants for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training pants",
    variants: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "M" },
    ],
    rating: 4.5,
    reviews: 85,
  },
  {
    id: "sw39",
    name: "Studio Training Hoodie",
    category: "Sportswear",
    price: 49.99,
    description: "Hoodie for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training hoodie",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.6,
    reviews: 90,
  },
  {
    id: "sw40",
    name: "Performance Training Joggers",
    category: "Sportswear",
    price: 54.99,
    description: "Joggers for high-performance training.",
    images: [
      "https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training joggers",
    variants: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "M" },
    ],
    rating: 4.5,
    reviews: 80,
  },
  {
    id: "sw41",
    name: "Studio Performance Hoodie",
    category: "Sportswear",
    price: 52.99,
    description: "Performance hoodie for studio workouts.",
    images: [
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance hoodie",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "L" },
    ],
    rating: 4.4,
    reviews: 70,
  },
  {
    id: "sw42",
    name: "All-Weather Training Shorts",
    category: "Sportswear",
    price: 38.99,
    description: "Shorts for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shorts",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.3,
    reviews: 60,
  },
  {
    id: "sw43",
    name: "Studio Performance Tank",
    category: "Sportswear",
    price: 29.99,
    description: "Performance tank for studio workouts.",
    images: [
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance tank",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.3,
    reviews: 55,
  },
  {
    id: "sw44",
    name: "All-Weather Training Tee",
    category: "Sportswear",
    price: 34.99,
    description: "Tee for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tee",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.4,
    reviews: 60,
  },
  {
    id: "sw45",
    name: "Studio Performance Shorts Pro",
    category: "Sportswear",
    price: 39.99,
    description: "Pro shorts for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance shorts",
    variants: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "L" },
    ],
    rating: 4.5,
    reviews: 70,
  },
  {
    id: "sw46",
    name: "All-Weather Training Tank",
    category: "Sportswear",
    price: 31.99,
    description: "Tank for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tank",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.3,
    reviews: 60,
  },
  {
    id: "sw47",
    name: "Studio Performance Tee Pro",
    category: "Sportswear",
    price: 36.99,
    description: "Pro tee for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance tee",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.4,
    reviews: 70,
  },
  {
    id: "sw48",
    name: "All-Weather Training Shorts Pro",
    category: "Sportswear",
    price: 41.99,
    description: "Pro shorts for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training shorts",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.3,
    reviews: 60,
  },
  {
    id: "sw49",
    name: "Studio Performance Tank Pro",
    category: "Sportswear",
    price: 32.99,
    description: "Pro tank for studio and gym workouts.",
    images: [
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "performance tank",
    variants: [
      { type: "Color", value: "Blue" },
      { type: "Size", value: "M" },
    ],
    rating: 4.3,
    reviews: 55,
  },
  {
    id: "sw50",
    name: "All-Weather Training Tee Pro",
    category: "Sportswear",
    price: 37.99,
    description: "Pro tee for all-weather outdoor training.",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    ],
    dataAiHint: "training tee",
    variants: [
      { type: "Color", value: "Black" },
      { type: "Size", value: "L" },
    ],
    rating: 4.4,
    reviews: 60,
  },
]
